CREATE DATABASE IF NOT EXISTS Property_DB;
USE Property_DB;

-- Drop tables if they exist to reset the schema
DROP TABLE IF EXISTS LISTING_PHOTOS;
DROP TABLE IF EXISTS LISTING_INFO;
DROP TABLE IF EXISTS LISTING;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS AGENT;

CREATE TABLE AGENT (
	AGENT_ID INT PRIMARY KEY UNIQUE NOT NULL,
    AGENT_EMAIL VARCHAR(30) NOT NULL,
    AGENT_PHONE CHAR(15) NOT NULL,
    AGENT_SOCIAL CHAR(15) NOT NULL
);

CREATE TABLE ACCOUNTS (
	ACCOUNTS_ID INT PRIMARY KEY UNIQUE NOT NULL,
    ACCOUNTS_FNAME VARCHAR(15),
    ACCOUNTS_LNAME VARCHAR(15),
    ACCOUNTS_EMAIL VARCHAR(30) NOT NULL,
    ACCOUNTS_PASSWORD VARCHAR(30) NOT NULL,
    ACCOUNTS_TYPE CHAR(10) NOT NULL,
    AGENT_ID INT,
    FOREIGN KEY (AGENT_ID) REFERENCES AGENT(AGENT_ID) ON DELETE CASCADE
);

CREATE TABLE LISTING (
	LISTING_ID INT PRIMARY KEY UNIQUE NOT NULL,
    LISTING_TITLE CHAR(30) NOT NULL,
    LISTING_DESCRIPTION VARCHAR(2000),
    CREATE_DATE DATETIME NOT NULL,
    LAST_UPDATE DATETIME NOT NULL,
    AGENT_ID INT NOT NULL, 
    FOREIGN KEY (AGENT_ID) REFERENCES AGENT(AGENT_ID) ON DELETE CASCADE
);

CREATE TABLE LISTING_INFO (
	LISTING_ID INT NOT NULL,
    LISTING_PRICE DECIMAL(12,2) NOT NULL,
    LISTING_ADDRESS VARCHAR(100) NOT NULL,
    LISTING_BEDROOM TINYINT,
    LISTING_BATHROOM TINYINT,
    LISTING_LIVINGROOM TINYINT,
    LISTING_GARAGE TINYINT,
    LISTING_YEAR SMALLINT,
    LISTING_SQFT SMALLINT,
    
    PRIMARY KEY (LISTING_ID),
    FOREIGN KEY (LISTING_ID) REFERENCES LISTING(LISTING_ID) ON DELETE CASCADE
);

CREATE TABLE LISTING_PHOTOS (
	PHOTO_ID     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	LISTING_ID   INT NOT NULL,
	PHOTO_DATA   MEDIUMBLOB NOT NULL,
	PHOTO_MIME   VARCHAR(50) NOT NULL,
    FOREIGN KEY (LISTING_ID) REFERENCES LISTING(LISTING_ID),
    INDEX (LISTING_ID)
);

 INSERT INTO ACCOUNTS (ACCOUNTS_ID, ACCOUNTS_FNAME, ACCOUNTS_LNAME, ACCOUNTS_EMAIL, ACCOUNTS_PASSWORD, ACCOUNTS_TYPE, AGENT_ID) VALUES
 ('1', 'Admin', 'Admin', 'Admin@House.com', '123', 'ADMIN', NULL);
 
 SELECT * from ACCOUNTS;
 
 